server:
  port: 9001 #???? ??

spring:
  application:
    name: discoveryservice # ??? ID

eureka:
  client:
    register-with-eureka: true # default : true
    fetch-registry: true # EUREKA ????? ?????? ??? ????? ??? ???? ???? ??
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

